version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04

    steps:
      - checkout

      - run:
          name: Compile
          command: g++ main.cpp -o main.run

      - run:
          name: Test
          command: ./main.run