version: 2
jobs:
  build:
    docker:
      - image: openjdk:8-jdk

    steps:
      - checkout

#     - run:
#         name: Compile
#         command: g++ main.cpp -o main.run
#
#     - run:
#         name: Test
#         command: ./main.run
      - run:
          name: dependencies
          command: gradle dependencies